-- MySQL Script generated by MySQL Workbench
-- Tue May  7 01:55:52 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema doley
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `doley` ;

-- -----------------------------------------------------
-- Schema doley
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `doley` DEFAULT CHARACTER SET utf8 ;
USE `doley` ;

-- -----------------------------------------------------
-- Table `doley`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doley`.`customer` ;

CREATE TABLE IF NOT EXISTS `doley`.`customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  `phone` INT NOT NULL,
  `discharge_date` DATE NOT NULL,
  `email` VARCHAR(255) NULL,
  `gender` VARCHAR(1) NULL,
  `postal_code` INT NULL,
  `right_image` TINYINT(1) NOT NULL DEFAULT 0,
  `birthdate` DATE NULL,
  `observations` LONGTEXT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doley`.`user_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doley`.`user_group` ;

CREATE TABLE IF NOT EXISTS `doley`.`user_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doley`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doley`.`user` ;

CREATE TABLE IF NOT EXISTS `doley`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NOT NULL,
  `group_id` INT NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `group_id`),
  INDEX `fk_user_group1_idx` (`group_id` ASC),
  CONSTRAINT `fk_user_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `doley`.`user_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doley`.`service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doley`.`service` ;

CREATE TABLE IF NOT EXISTS `doley`.`service` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `duration` INT NULL,
  `price` DECIMAL NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doley`.`appoinment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doley`.`appoinment` ;

CREATE TABLE IF NOT EXISTS `doley`.`appoinment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `day` DATE NOT NULL,
  `pay_and_signal` TINYINT(1) NOT NULL DEFAULT 0,
  `absence` TINYINT(1) NOT NULL DEFAULT 0,
  `cancellation` TINYINT(1) NOT NULL DEFAULT 0,
  `customer_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `service_id` INT NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `customer_id`, `user_id`),
  INDEX `fk_appoinment_customer_idx` (`customer_id` ASC),
  INDEX `fk_appoinment_user1_idx` (`user_id` ASC),
  INDEX `fk_appoinment_services1_idx` (`service_id` ASC),
  CONSTRAINT `fk_appoinment_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `doley`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_appoinment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `doley`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_appoinment_services1`
    FOREIGN KEY (`service_id`)
    REFERENCES `doley`.`service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doley`.`product_family_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doley`.`product_family_type` ;

CREATE TABLE IF NOT EXISTS `doley`.`product_family_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doley`.`provider`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doley`.`provider` ;

CREATE TABLE IF NOT EXISTS `doley`.`provider` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `phone` INT NULL,
  `cif` VARCHAR(45) NULL,
  `business_name` VARCHAR(255) NULL,
  `address` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doley`.`brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doley`.`brand` ;

CREATE TABLE IF NOT EXISTS `doley`.`brand` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doley`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doley`.`product` ;

CREATE TABLE IF NOT EXISTS `doley`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `purchase_price` DECIMAL NOT NULL,
  `use_and_throw` TINYINT(1) NOT NULL DEFAULT 0,
  `sale_price` DECIMAL NOT NULL,
  `size` DECIMAL NULL,
  `product_family_type_id` INT NOT NULL,
  `provider_id` INT NOT NULL,
  `brand_id` INT NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `provider_id`, `brand_id`),
  INDEX `fk_product_product_family_type1_idx` (`product_family_type_id` ASC),
  INDEX `fk_product_provider1_idx` (`provider_id` ASC),
  INDEX `fk_product_brand1_idx` (`brand_id` ASC),
  CONSTRAINT `fk_product_product_family_type1`
    FOREIGN KEY (`product_family_type_id`)
    REFERENCES `doley`.`product_family_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_provider1`
    FOREIGN KEY (`provider_id`)
    REFERENCES `doley`.`provider` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_brand1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `doley`.`brand` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doley`.`stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doley`.`stock` ;

CREATE TABLE IF NOT EXISTS `doley`.`stock` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` DECIMAL NOT NULL,
  `product_id` INT NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `product_id`),
  INDEX `fk_stock_product1_idx` (`product_id` ASC),
  CONSTRAINT `fk_stock_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `doley`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doley`.`purchase_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doley`.`purchase_order` ;

CREATE TABLE IF NOT EXISTS `doley`.`purchase_order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` DECIMAL NOT NULL,
  `arrival_date` DATE NULL,
  `purchase_date` DATE NOT NULL,
  `price` DECIMAL NOT NULL,
  `estimated_arrival_date` DATE NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doley`.`purchase_order_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doley`.`purchase_order_product` ;

CREATE TABLE IF NOT EXISTS `doley`.`purchase_order_product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `purchase_order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `purchase_order_id`, `product_id`),
  INDEX `fk_purchase_order_product_purchase_order1_idx` (`purchase_order_id` ASC),
  INDEX `fk_purchase_order_product_product1_idx` (`product_id` ASC),
  CONSTRAINT `fk_purchase_order_product_purchase_order1`
    FOREIGN KEY (`purchase_order_id`)
    REFERENCES `doley`.`purchase_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_purchase_order_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `doley`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doley`.`order_delivery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doley`.`order_delivery` ;

CREATE TABLE IF NOT EXISTS `doley`.`order_delivery` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `real_price` DECIMAL NOT NULL,
  `arrival_date` DATE NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `product_id`),
  INDEX `fk_order_delivery_product1_idx` (`product_id` ASC),
  CONSTRAINT `fk_order_delivery_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `doley`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doley`.`allergen_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doley`.`allergen_type` ;

CREATE TABLE IF NOT EXISTS `doley`.`allergen_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doley`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doley`.`employee` ;

CREATE TABLE IF NOT EXISTS `doley`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `dni` VARCHAR(15) NOT NULL,
  `social_security_number` INT NOT NULL,
  `entry_date` DATE NOT NULL,
  `departure_date` DATE NOT NULL,
  `phone` INT NOT NULL,
  `account_number` INT NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL,
  `user_id` INT NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_employee_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_employee_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `doley`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doley`.`customer_service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doley`.`customer_service` ;

CREATE TABLE IF NOT EXISTS `doley`.`customer_service` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `service_id` INT NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `customer_id`, `service_id`, `updated_at`),
  INDEX `fk_customer_service_customers1_idx` (`customer_id` ASC),
  INDEX `fk_customer_service_services2_idx` (`service_id` ASC),
  CONSTRAINT `fk_customer_service_customers1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `doley`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_service_services2`
    FOREIGN KEY (`service_id`)
    REFERENCES `doley`.`service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doley`.`product_allergen_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doley`.`product_allergen_type` ;

CREATE TABLE IF NOT EXISTS `doley`.`product_allergen_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `allergen_type_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`, `allergen_type_id`, `product_id`),
  INDEX `fk_customer_allergen_type_allergen_type1_idx` (`allergen_type_id` ASC),
  INDEX `fk_customer_allergen_type_product1_idx` (`product_id` ASC),
  CONSTRAINT `fk_customer_allergen_type_allergen_type1`
    FOREIGN KEY (`allergen_type_id`)
    REFERENCES `doley`.`allergen_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_allergen_type_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `doley`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doley`.`customer_allergen_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doley`.`customer_allergen_type` ;

CREATE TABLE IF NOT EXISTS `doley`.`customer_allergen_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `allergen_type_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `allergen_type_id`, `customer_id`),
  INDEX `fk_customer_allergen_type_allergen_type2_idx` (`allergen_type_id` ASC),
  INDEX `fk_customer_allergen_type_customer1_idx` (`customer_id` ASC),
  CONSTRAINT `fk_customer_allergen_type_allergen_type2`
    FOREIGN KEY (`allergen_type_id`)
    REFERENCES `doley`.`allergen_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_allergen_type_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `doley`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doley`.`customer_product_purchase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doley`.`customer_product_purchase` ;

CREATE TABLE IF NOT EXISTS `doley`.`customer_product_purchase` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `purchase_date` DATETIME NOT NULL,
  `customer_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `customer_id`, `product_id`),
  INDEX `fk_customer_product_purchase_customer1_idx` (`customer_id` ASC),
  INDEX `fk_customer_product_purchase_product1_idx` (`product_id` ASC),
  CONSTRAINT `fk_customer_product_purchase_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `doley`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_product_purchase_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `doley`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doley`.`exception`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doley`.`exception` ;

CREATE TABLE IF NOT EXISTS `doley`.`exception` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `exception` VARCHAR(255) NOT NULL,
  `class` VARCHAR(255) NULL,
  `method` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  `exceptioncol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doley`.`customer_service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doley`.`customer_service` ;

CREATE TABLE IF NOT EXISTS `doley`.`customer_service` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `service_id` INT NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `customer_id`, `service_id`, `updated_at`),
  INDEX `fk_customer_service_customers1_idx` (`customer_id` ASC),
  INDEX `fk_customer_service_services2_idx` (`service_id` ASC),
  CONSTRAINT `fk_customer_service_customers1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `doley`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_service_services2`
    FOREIGN KEY (`service_id`)
    REFERENCES `doley`.`service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doley`.`product_service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doley`.`product_service` ;

CREATE TABLE IF NOT EXISTS `doley`.`product_service` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `services_id` INT NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `product_id`, `services_id`),
  INDEX `fk_product_service_product1_idx` (`product_id` ASC),
  INDEX `fk_product_service_services1_idx` (`services_id` ASC),
  CONSTRAINT `fk_product_service_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `doley`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_service_services1`
    FOREIGN KEY (`services_id`)
    REFERENCES `doley`.`service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
